[package]
name = "part2"
version = "0.1.0"
authors = ["Mateusz Najda <mateusznajda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.8"
num-integer = "0.1"
